<?php
ob_start();
?>

<div class="card mb-3">
  <img src="images/bible_ouverte_reduite2.jpg" class="card-img-top" alt="bible ouverte" >
  <div class="card-body">
    <h1 class="card-title">LA FIN DE TOUTES CHOSES</h1>
    <p class="card-text m-5">
    <p>
    1- La consommation de toutes choses comprend l’enlèvement de l’Église, la période de tribulation, le retour visible, personnel et glorieux de Jésus-Christ, le royaume messianique de mille ans, la résurrection des morts, le jugement dernier et l’accomplissement du royaume de Christ dans les nouveaux cieux et sur la nouvelle terre. Satan avec ses armées et tous les hommes morts sans Christ seront finalement séparés de la présence de Dieu, endurant la punition éternelle de l’enfer. Tous ceux qui ont été rachetés par Christ du royaume des ténèbres vers le royaume de la lumière seront pour toujours dans la présence de Dieu.</br>

 

Jérémie 30:7: Quel malheur ! C’est un jour terrible, un jour sans pareil; c’est un temps de détresse pour les descendants de Jacob! Et pourtant ils en sortiront sains et saufs. Daniel 9:27: Pendant la dernière période de sept ans, il imposera de dures obligations à un grand nombre de gens. Au bout de trois ans et demi, il fera même cesser les sacrifices et les offrandes. Ce dévastateur accomplira ses oeuvres abominables avec rapidité, jusqu’à ce que la fin qui a été décidée s’abatte sur lui.</br> 
Apocalypse 6:17: Car le grand jour de leur colère est arrivé et qui pourrait lui résister ?</br>
Actes 1:11: …et leur dirent: Hommes de Galilée, pourquoi restez-vous là à regarder le ciel ? Ce Jésus, qui vous a été enlevé pour aller au ciel, reviendra de la même manière que vous l’avez vu y partir.</br> 
Matthieu 24:27-31: Comme l’éclair brille à travers le ciel de l’est à l’ouest, ainsi viendra le Fils de l’homme. Où que soit le cadavre, là se rassembleront les vautours. Aussitôt après la détresse de ces jours-là, le soleil s’obscurcira, la lune ne donnera plus sa clarté, les étoiles tomberont du ciel et les puissances des cieux seront ébranlées. Alors, le signe du Fils de l’homme apparaîtra dans le ciel; alors, tous les peuples de la terre se lamenteront, ils verront le Fils de l’homme arriver sur les nuages du ciel avec beaucoup de puissance et de gloire. La grande trompette sonnera et il enverra ses anges aux quatre coins de la terre: ils rassembleront ceux qu’il a choisis, d’un bout du monde à l’autre.</br> 
Apocalypse 19:11-16: Puis je vis le ciel ouvert, et un cheval blanc apparut. Celui qui le monte s’appelle Fidèle et Véritable; il juge et combat avec justice. Ses yeux flamboyaient comme du feu et il avait de nombreuses couronnes sur la tête. Il portait un nom inscrit qu’il est le seul à connaître. Il était vêtu d’un manteau couvert de sang. Il s’appelle La parole de Dieu. Les armées du ciel le suivaient, montées sur des chevaux blancs et vêtues d’un fin tissu de lin, blanc et pur. De sa bouche sortait une épée aiguë destinée à frapper les nations. Il les dirigera avec une autorité de fer, et il écrasera le raisin dans le pressoir de l’ardente colère du Dieu tout-puissant. Sur son manteau et sur sa jambe le nom suivant était inscrit: Roi des rois et Seigneur des seigneurs.</br>
Apocalypse 20:1-10: Puis je vis un ange descendre du ciel; il tenait à la main la clé de l’abîme et une énorme chaîne. Il saisit le hdragon, le serpent ancien, c’est-à-dire le diable ou Satan, et il l’enchaîna pour mille ans. L’ange le jeta dans l’abîme, qu’il ferma à clé et scella au-dessus de lui, afin que le dragon ne puisse plus égarer les nations jusqu’à ce que les mille ans soient passés. Après cela, il doit être relâché pour un peu de temps. Ensuite je vis des trônes: ceux qui siégeaient dessus reçurent le pouvoir de juger. Je vis aussi les âmes de ceux qui avaient été exécutés pour leur fidélité à la vérité révélée par Jésus et à la parole de Dieu. Ils n’avaient pas adoré la bête, ni sa statue, et ils n’avaient pas reçu la marque de la bête sur le front, ni sur la main. Ils revinrent à la vie et régnèrent avec le Christ pendant mille ans. Les autres morts ne revinrent pas à la vie avant que les mille ans soient passés. C’est la première résurrection. Heureux ceux qui ont part à cette première résurrection! Ils appartiennent à Dieu et la seconde mort n’a pas de pouvoir sur eux; ils seront prêtres de Dieu et du Christ, et ils régneront avec le Christ pendant les mille ans. Quand les mille ans seront passés, Satan sera relâché de sa prison, et il s’en ira tromper les nations répandues dans le monde entier, c’est-à-dire Gog et Magog. Il les rassemblera pour le combat, et ils seront aussi nombreux que les grains de sable au bord de la mer. Les voici qui s’avancent sur toute l’étendue de la terre, et ils encerclent le camp du peuple de Dieu, la ville aimée de Dieu. Mais le feu descend du ciel et les détruit. Alors le diable, qui les trompait, est jeté dans le lac de soufre enflammé, où se trouvent déjà la bête et le faux prophète. Ils y seront tourmentés jour et nuit pour toujours.</br>
Apocalypse 20:11-15: Puis je vis un grand trône blanc et celui qui y siège. La terre et le ciel s’enfuirent loin de lui, et on ne les revit plus. Ensuite, je vis les morts, grands et petits, debout devant le trône. Des livres furent ouverts. Un autre livre encore fut ouvert, le livre de vie. Les morts furent jugés selon ce qu’ils avaient fait, d’après ce qui était écrit dans les livres. La mer rendit les morts qu’elle contenait. La mort et le monde des morts rendirent aussi leurs morts. Et tous furent jugés selon ce qu’ils avaient fait. La mort et le monde des morts furent jetés dans le lac enflammé. Ce lac est la seconde mort. Quiconque n’avait pas son nom inscrit dans le livre de vie fut jeté dans le lac enflammé.</br> 
Apocalypse 21:1-4: Alors je vis un nouveau ciel et une nouvelle terre. Le premier ciel et la première terre avaient disparu, et il n’y avait plus de mer. Et je vis la ville sainte, la nouvelle Jérusalem, qui descendait du ciel, envoyée par Dieu, prête comme une épouse qui s’est faite belle pour aller à la rencontre de son mari. J’entendis une voix forte qui venait du trône et disait: Maintenant la demeure de Dieu est parmi les hommes ! Il demeurera avec eux et ils seront ses peuples. Dieu lui-même sera avec eux, il sera leur Dieu. Il essuiera toute larme de leurs yeux. Il n’y aura plus de mort, il n’y aura plus ni deuil, ni lamentations, ni douleur. En effet, les choses anciennes auront disparu. 
    </p>

    </p>

  </div>
</div>

<?php
$content= ob_get_clean();

require_once 'template.php';